### ISSUE TITLE
Implementation report out of date

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/battery#65]
Firefox Android doesn't seem to support the Battery Status API? Checked on Firefox 121 on Android.

**Comment by marcoscaceres** [comment]
It was removed in Firefox 52:
https://www.mozilla.org/en-US/firefox/52.0/releasenotes/

"Removed Battery Status API to reduce fingerprinting of users by trackers"

**Comment by anssiko** [comment]
Thank you for your attention to our group's specifications.

I have submitted a fix to refer to the wpt.fyi results: #66

You should know that the DAS WG invests in test automation of its deliverables and https://wpt.fyi/results/battery-status coverage is expected to improve with automation. This is why I think it is appropriate to refer to the wpt.fyi results already now even if we know they're still WIP. If you are interested in contributing help advance test automation, we can help you get started.

Per process, an implementation report is not expected at a Working Draft stage. Regardless, such static implementation reports may be produced from time to time for the benefit of the diverse browser ecosystem not integrated into wpt.fyi yet (see e.g. https://caniuse.com/battery-status) or when warranted by certain transitions.

**Comment by marcoscaceres** [comment]
How would test results change with automation? The spec is only implemented by one engine? 

Like with #66, the wtp results will never change because it’s only implemented by one engine (and there’s zero chance that will change). 

You seem to want to have it both ways: use WPT.fyi for results, while relying on known-to-be somewhat dubious and incomplete results from caniuse. 

Caniuse is not a measure of interop in the way WPT does. No one would cite caniuse as a measure of interop with any degree of seriousness.
